-- Mock data for testing the page assignment feature
-- Insert sample resources for each assigned page

-- 幼儿英语 (Young Children) - 4 resources
INSERT INTO resources (
    title,
    highlights,
    "resourceInfo",
    category,
    assigned_page,
    price,
    "isWeeklyHot",
    "isNew",
    content,
    "coverImage",
    "resourceUrl",
    "createdAt",
    "updatedAt"
) VALUES 
(
    'Peppa Pig 粉红猪小妹全集',
    '适合3-6岁幼儿英语启蒙，生活化场景，简单日常对话',
    '每集5分钟，共200集。内容贴近幼儿生活，语速适中，发音清晰标准。',
    '幼儿英语启蒙',
    '幼儿英语',
    29.9,
    true,
    false,
    '<h2>资源介绍</h2><p>Peppa Pig是最受欢迎的幼儿英语启蒙动画之一。</p>',
    '',
    'https://example.com/peppa-pig',
    NOW(),
    NOW()
),
(
    'Super Simple Songs 儿歌合集',
    '经典英文儿歌，朗朗上口，适合磨耳朵',
    '包含100首经典英文儿歌，配有动画MV，帮助幼儿建立英语语感。',
    '幼儿英语启蒙',
    '幼儿英语',
    19.9,
    false,
    true,
    '<h2>资源介绍</h2><p>Super Simple Songs是专为幼儿设计的英文儿歌系列。</p>',
    '',
    'https://example.com/super-simple-songs',
    NOW(),
    NOW()
),
(
    'Maisy Mouse 小鼠波波',
    '温馨可爱的动画，培养良好生活习惯',
    '每集10分钟，共44集。通过小老鼠Maisy的日常生活，学习基础英语词汇。',
    '幼儿英语启蒙',
    '幼儿英语',
    24.9,
    false,
    false,
    '<h2>资源介绍</h2><p>Maisy Mouse适合3-5岁幼儿观看学习。</p>',
    '',
    'https://example.com/maisy-mouse',
    NOW(),
    NOW()
),
(
    'Alphablocks 字母积木',
    '自然拼读启蒙神器，寓教于乐',
    '通过有趣的字母积木角色，帮助孩子掌握自然拼读规则。',
    '幼儿英语启蒙',
    '幼儿英语',
    34.9,
    true,
    true,
    '<h2>资源介绍</h2><p>BBC出品的自然拼读动画，深受家长好评。</p>',
    '',
    'https://example.com/alphablocks',
    NOW(),
    NOW()
);

-- 少儿英语 (Children) - 4 resources
INSERT INTO resources (
    title,
    highlights,
    "resourceInfo",
    category,
    assigned_page,
    price,
    "isWeeklyHot",
    "isNew",
    content,
    "coverImage",
    "resourceUrl",
    "createdAt",
    "updatedAt"
) VALUES 
(
    'Magic School Bus 神奇校车',
    '科学知识+英语学习，一举两得',
    '52集科普动画，涵盖物理、化学、生物等多个领域，适合7-12岁儿童。',
    '少儿英语基础',
    '少儿英语',
    39.9,
    true,
    false,
    '<h2>资源介绍</h2><p>跟随卷毛老师和神奇校车，探索科学世界。</p>',
    '',
    'https://example.com/magic-school-bus',
    NOW(),
    NOW()
),
(
    'Harry Potter 哈利波特有声书',
    '经典奇幻小说，提升英语阅读能力',
    '全7部有声书，由Jim Dale朗读，发音纯正，适合有一定基础的少儿。',
    '少儿英语基础',
    '少儿英语',
    49.9,
    false,
    true,
    '<h2>资源介绍</h2><p>沉浸式英语学习，培养阅读兴趣。</p>',
    '',
    'https://example.com/harry-potter',
    NOW(),
    NOW()
),
(
    'National Geographic Kids 国家地理儿童版',
    '探索世界，拓展视野',
    '精选100期国家地理儿童杂志，配有精美图片和有趣的科普文章。',
    '少儿英语基础',
    '少儿英语',
    44.9,
    true,
    false,
    '<h2>资源介绍</h2><p>通过真实的世界探索，学习地道英语。</p>',
    '',
    'https://example.com/nat-geo-kids',
    NOW(),
    NOW()
),
(
    'Charlie and the Chocolate Factory 查理和巧克力工厂',
    '罗尔德·达尔经典作品，激发想象力',
    '有声书+电子书，适合8-12岁儿童，培养英语阅读习惯。',
    '少儿英语基础',
    '少儿英语',
    29.9,
    false,
    true,
    '<h2>资源介绍</h2><p>奇幻冒险故事，提升英语阅读兴趣。</p>',
    '',
    'https://example.com/charlie-chocolate',
    NOW(),
    NOW()
);

-- 青少年英语 (Teenagers) - 4 resources
INSERT INTO resources (
    title,
    highlights,
    "resourceInfo",
    category,
    assigned_page,
    price,
    "isWeeklyHot",
    "isNew",
    content,
    "coverImage",
    "resourceUrl",
    "createdAt",
    "updatedAt"
) VALUES 
(
    'Friends 老友记全10季',
    '经典美剧，学习地道口语表达',
    '240集完整版，中英双字幕，适合13-18岁青少年提升听力和口语。',
    '青少年英语进阶',
    '青少年英语',
    59.9,
    true,
    false,
    '<h2>资源介绍</h2><p>通过情景喜剧，学习日常英语对话。</p>',
    '',
    'https://example.com/friends',
    NOW(),
    NOW()
),
(
    'The Hunger Games 饥饿游戏三部曲',
    '青少年必读小说，提升阅读能力',
    '有声书+电子书，扣人心弦的故事情节，适合英语进阶学习。',
    '青少年英语进阶',
    '青少年英语',
    54.9,
    false,
    true,
    '<h2>资源介绍</h2><p>反乌托邦题材，培养批判性思维。</p>',
    '',
    'https://example.com/hunger-games',
    NOW(),
    NOW()
),
(
    'TED-Ed 教育频道精选',
    '开拓思维，学习演讲技巧',
    '100个精选TED-Ed视频，涵盖科学、历史、艺术等多个领域。',
    'TED演讲',
    '青少年英语',
    39.9,
    true,
    true,
    '<h2>资源介绍</h2><p>通过优质演讲，提升英语听力和思维能力。</p>',
    '',
    'https://example.com/ted-ed',
    NOW(),
    NOW()
),
(
    'The New York Times 纽约时报精选文章',
    '时事新闻，提升阅读理解',
    '每周更新，精选适合青少年的新闻文章，配有词汇解析。',
    '青少年英语进阶',
    '青少年英语',
    49.9,
    false,
    false,
    '<h2>资源介绍</h2><p>了解世界，提升英语阅读和写作能力。</p>',
    '',
    'https://example.com/nyt-articles',
    NOW(),
    NOW()
);

-- 科普纪录片 (Documentaries) - 4 resources
INSERT INTO resources (
    title,
    highlights,
    "resourceInfo",
    category,
    assigned_page,
    price,
    "isWeeklyHot",
    "isNew",
    content,
    "coverImage",
    "resourceUrl",
    "createdAt",
    "updatedAt"
) VALUES 
(
    'Blue Planet II 蓝色星球2',
    'BBC自然纪录片巨制，探索海洋奥秘',
    '7集完整版，4K超清画质，英文原声+中英字幕，适合全年龄段。',
    '科普纪录片',
    '科普纪录片',
    69.9,
    true,
    false,
    '<h2>资源介绍</h2><p>大卫·爱登堡爵士解说，领略海洋之美。</p>',
    '',
    'https://example.com/blue-planet-2',
    NOW(),
    NOW()
),
(
    'Planet Earth 地球脉动',
    '史诗级自然纪录片，震撼视觉体验',
    '11集完整版，展现地球上最壮观的自然景观和野生动物。',
    '科普纪录片',
    '科普纪录片',
    64.9,
    true,
    false,
    '<h2>资源介绍</h2><p>BBC经典纪录片，必看之作。</p>',
    '',
    'https://example.com/planet-earth',
    NOW(),
    NOW()
),
(
    'Cosmos 宇宙时空之旅',
    '探索宇宙奥秘，启发科学思维',
    '13集科学纪录片，由天体物理学家Neil deGrasse Tyson主持。',
    '科普纪录片',
    '科普纪录片',
    59.9,
    false,
    true,
    '<h2>资源介绍</h2><p>从宇宙大爆炸到人类文明，一次奇妙的时空之旅。</p>',
    '',
    'https://example.com/cosmos',
    NOW(),
    NOW()
),
(
    'Our Planet 我们的星球',
    'Netflix原创，关注环境保护',
    '8集纪录片，展现地球生态系统的多样性和脆弱性。',
    '科普纪录片',
    '科普纪录片',
    54.9,
    false,
    true,
    '<h2>资源介绍</h2><p>大卫·爱登堡爵士解说，呼吁保护地球家园。</p>',
    '',
    'https://example.com/our-planet',
    NOW(),
    NOW()
);
